using System.Globalization;
using System.Text.Json;
using QiblaNow.Core;
using QiblaNow.Core.Abstractions;
using QiblaNow.Core.Models;

namespace QiblaNow.Core.Tests;

/// <summary>
/// Oracle acceptance tests driven by JSON datasets generated by the PrayTimes v3.2 CLI.
///
/// Each dataset was produced with:
///   node cli.js --date ... --lat ... --lon ... --timezone UTC
///              --method ... --asr ... --highLats OneSeventh --rounding nearest --json
///
/// Expected times are UTC wall-clock strings (HH:mm).
/// Our calculator always outputs DateTimeOffset with UTC offset, so .ToString("HH:mm")
/// reflects UTC time directly.
///
/// Do NOT hand-edit the JSON files or tweak assertions to match the implementation.
/// If a test fails, fix the implementation.
/// </summary>
public class OraclePrayerTimesTests
{
    private static readonly IPrayerTimesCalculator Calculator = new PrayerTimesCalculator();

    // ── Dataset loading ────────────────────────────────────────────────────

    private sealed record OracleDataset(
        OracleConfig Config,
        OracleTimes UtcTimes);

    private sealed record OracleConfig(
        string Date,
        double Lat,
        double Lon,
        string Method,
        string Asr,
        string HighLats);

    private sealed record OracleTimes(
        string Fajr,
        string Sunrise,
        string Dhuhr,
        string Asr,
        string Maghrib,
        string Isha);

    private static OracleDataset LoadDataset(string fileName)
    {
        var path = Path.Combine(
            AppContext.BaseDirectory,
            "TestData", "praytimes", fileName);

        var json = File.ReadAllText(path);
        using var doc = JsonDocument.Parse(json);
        var root = doc.RootElement;

        var cfg = root.GetProperty("config");
        var t   = root.GetProperty("utc_times");

        return new OracleDataset(
            new OracleConfig(
                cfg.GetProperty("date").GetString()!,
                cfg.GetProperty("lat").GetDouble(),
                cfg.GetProperty("lon").GetDouble(),
                cfg.GetProperty("method").GetString()!,
                cfg.GetProperty("asr").GetString()!,
                cfg.GetProperty("highLats").GetString()!),
            new OracleTimes(
                t.GetProperty("fajr").GetString()!,
                t.GetProperty("sunrise").GetString()!,
                t.GetProperty("dhuhr").GetString()!,
                t.GetProperty("asr").GetString()!,
                t.GetProperty("maghrib").GetString()!,
                t.GetProperty("isha").GetString()!));
    }

    private static PrayerCalculationSettings BuildSettings(OracleConfig cfg)
    {
        var method = cfg.Method switch
        {
            "MWL"     => CalculationMethod.MuslimWorldLeague,
            "ISNA"    => CalculationMethod.ISNA,
            "Makkah"  => CalculationMethod.UmmAlQura,
            "Egypt"   => CalculationMethod.EgyptianGeneralAuthority,
            "Karachi" => CalculationMethod.Karachi,
            _         => throw new ArgumentException($"Unknown method: {cfg.Method}")
        };

        var madhab = cfg.Asr == "Hanafi" ? Madhab.Hanafi : Madhab.Shafi;

        var highLat = cfg.HighLats switch
        {
            "OneSeventh"   => HighLatitudeRule.SeventhOfNight,
            "NightMiddle"  => HighLatitudeRule.MiddleOfNight,
            _              => HighLatitudeRule.SeventhOfNight
        };

        return new PrayerCalculationSettings
        {
            Method           = method,
            Madhab           = madhab,
            HighLatitudeRule = highLat
        };
    }

    private static string Fmt(DateTimeOffset t) =>
        t.ToString("HH:mm", CultureInfo.InvariantCulture);

    private static async Task<DailyPrayerSchedule> ComputeSchedule(OracleDataset ds)
    {
        var dateParts = ds.Config.Date.Split('-').Select(int.Parse).ToArray();
        var date = new DateTimeOffset(dateParts[0], dateParts[1], dateParts[2],
            0, 0, 0, TimeSpan.Zero);

        var location = new LocationSnapshot(
            LocationMode.Manual, ds.Config.Lat, ds.Config.Lon, ds.Config.Date);

        return await Calculator.CalculateDailyScheduleAsync(location, date, BuildSettings(ds.Config));
    }

    // ── Oracle: London 2026-03-02 ──────────────────────────────────────────

    [Fact]
    public async Task Oracle_London_2026_03_02_MatchesAllPrayers()
    {
        var ds = LoadDataset("london-2026-03-02.json");
        var schedule = await ComputeSchedule(ds);

        Assert.NotNull(schedule);
        Assert.Equal(6, schedule.Prayers.Count);

        var fajr    = schedule.GetPrayer(PrayerType.Fajr)!.Value;
        var sunrise = schedule.GetPrayer(PrayerType.Sunrise)!.Value;
        var dhuhr   = schedule.GetPrayer(PrayerType.Dhuhr)!.Value;
        var asr     = schedule.GetPrayer(PrayerType.Asr)!.Value;
        var maghrib = schedule.GetPrayer(PrayerType.Maghrib)!.Value;
        var isha    = schedule.GetPrayer(PrayerType.Isha)!.Value;

        Assert.Equal(ds.UtcTimes.Fajr,    Fmt(fajr.DateTime));
        Assert.Equal(ds.UtcTimes.Sunrise,  Fmt(sunrise.DateTime));
        Assert.Equal(ds.UtcTimes.Dhuhr,   Fmt(dhuhr.DateTime));
        Assert.Equal(ds.UtcTimes.Asr,     Fmt(asr.DateTime));
        Assert.Equal(ds.UtcTimes.Maghrib, Fmt(maghrib.DateTime));
        Assert.Equal(ds.UtcTimes.Isha,    Fmt(isha.DateTime));
    }

    // ── Oracle: London 2026-03-28 ──────────────────────────────────────────

    [Fact]
    public async Task Oracle_London_2026_03_28_MatchesAllPrayers()
    {
        var ds = LoadDataset("london-2026-03-28.json");
        var schedule = await ComputeSchedule(ds);

        Assert.NotNull(schedule);

        Assert.Equal(ds.UtcTimes.Fajr,    Fmt(schedule.GetPrayer(PrayerType.Fajr)!.Value.DateTime));
        Assert.Equal(ds.UtcTimes.Sunrise,  Fmt(schedule.GetPrayer(PrayerType.Sunrise)!.Value.DateTime));
        Assert.Equal(ds.UtcTimes.Dhuhr,   Fmt(schedule.GetPrayer(PrayerType.Dhuhr)!.Value.DateTime));
        Assert.Equal(ds.UtcTimes.Asr,     Fmt(schedule.GetPrayer(PrayerType.Asr)!.Value.DateTime));
        Assert.Equal(ds.UtcTimes.Maghrib, Fmt(schedule.GetPrayer(PrayerType.Maghrib)!.Value.DateTime));
        Assert.Equal(ds.UtcTimes.Isha,    Fmt(schedule.GetPrayer(PrayerType.Isha)!.Value.DateTime));
    }

    // ── Oracle: London 2026-03-29 (first BST day, UTC output) ─────────────

    [Fact]
    public async Task Oracle_London_2026_03_29_MatchesAllPrayers()
    {
        var ds = LoadDataset("london-2026-03-29.json");
        var schedule = await ComputeSchedule(ds);

        Assert.NotNull(schedule);

        Assert.Equal(ds.UtcTimes.Fajr,    Fmt(schedule.GetPrayer(PrayerType.Fajr)!.Value.DateTime));
        Assert.Equal(ds.UtcTimes.Sunrise,  Fmt(schedule.GetPrayer(PrayerType.Sunrise)!.Value.DateTime));
        Assert.Equal(ds.UtcTimes.Dhuhr,   Fmt(schedule.GetPrayer(PrayerType.Dhuhr)!.Value.DateTime));
        Assert.Equal(ds.UtcTimes.Asr,     Fmt(schedule.GetPrayer(PrayerType.Asr)!.Value.DateTime));
        Assert.Equal(ds.UtcTimes.Maghrib, Fmt(schedule.GetPrayer(PrayerType.Maghrib)!.Value.DateTime));
        Assert.Equal(ds.UtcTimes.Isha,    Fmt(schedule.GetPrayer(PrayerType.Isha)!.Value.DateTime));
    }

    // ── Oracle: Reykjavik 2026-01-15 (high-latitude rule active) ──────────

    [Fact]
    public async Task Oracle_Reykjavik_2026_01_15_MatchesAllPrayers()
    {
        var ds = LoadDataset("reykjavik-2026-01-15.json");
        var schedule = await ComputeSchedule(ds);

        Assert.NotNull(schedule);

        Assert.Equal(ds.UtcTimes.Fajr,    Fmt(schedule.GetPrayer(PrayerType.Fajr)!.Value.DateTime));
        Assert.Equal(ds.UtcTimes.Sunrise,  Fmt(schedule.GetPrayer(PrayerType.Sunrise)!.Value.DateTime));
        Assert.Equal(ds.UtcTimes.Dhuhr,   Fmt(schedule.GetPrayer(PrayerType.Dhuhr)!.Value.DateTime));
        Assert.Equal(ds.UtcTimes.Asr,     Fmt(schedule.GetPrayer(PrayerType.Asr)!.Value.DateTime));
        Assert.Equal(ds.UtcTimes.Maghrib, Fmt(schedule.GetPrayer(PrayerType.Maghrib)!.Value.DateTime));
        Assert.Equal(ds.UtcTimes.Isha,    Fmt(schedule.GetPrayer(PrayerType.Isha)!.Value.DateTime));
    }

    // ── Oracle: Makkah 2026-03-02 (UmmAlQura – isha = 90 min) ────────────

    [Fact]
    public async Task Oracle_Makkah_2026_03_02_MatchesAllPrayers()
    {
        var ds = LoadDataset("makkah-2026-03-02.json");
        var schedule = await ComputeSchedule(ds);

        Assert.NotNull(schedule);

        Assert.Equal(ds.UtcTimes.Fajr,    Fmt(schedule.GetPrayer(PrayerType.Fajr)!.Value.DateTime));
        Assert.Equal(ds.UtcTimes.Sunrise,  Fmt(schedule.GetPrayer(PrayerType.Sunrise)!.Value.DateTime));
        Assert.Equal(ds.UtcTimes.Dhuhr,   Fmt(schedule.GetPrayer(PrayerType.Dhuhr)!.Value.DateTime));
        Assert.Equal(ds.UtcTimes.Asr,     Fmt(schedule.GetPrayer(PrayerType.Asr)!.Value.DateTime));
        Assert.Equal(ds.UtcTimes.Maghrib, Fmt(schedule.GetPrayer(PrayerType.Maghrib)!.Value.DateTime));
        Assert.Equal(ds.UtcTimes.Isha,    Fmt(schedule.GetPrayer(PrayerType.Isha)!.Value.DateTime));
    }
}
