using QiblaNow.Core.Models;

namespace QiblaNow.Core.Tests;

public class PrayerTimesCalculatorTests
{
    private readonly PrayerTimesCalculator _calculator = new();

    // ── Mountain View (western hemisphere – prayers cross midnight UTC) ──────

    /// <summary>
    /// Regression test for the primary bug: ToDate clamped hours > 23,
    /// corrupting Maghrib/Isha at western longitudes where UTC times exceed 24h.
    /// Reference values generated by PrayTimes JS v3.2 CLI.
    /// </summary>
    [Fact]
    public async Task MountainView_MWL_MaghribAndIsha_FallOnNextUtcDay()
    {
        var schedule = await ComputeSchedule(37.3861, -122.0839, 2026, 3, 12,
            CalculationMethod.MuslimWorldLeague);

        // Maghrib/Isha must be on March 13 UTC (next day) — not clamped to March 12
        AssertUtc(schedule, PrayerType.Fajr,    2026, 3, 12, 12, 57);
        AssertUtc(schedule, PrayerType.Sunrise,  2026, 3, 12, 14, 24);
        AssertUtc(schedule, PrayerType.Dhuhr,   2026, 3, 12, 20, 18);
        AssertUtc(schedule, PrayerType.Asr,     2026, 3, 12, 23, 39);
        AssertUtc(schedule, PrayerType.Maghrib, 2026, 3, 13,  2, 14);
        AssertUtc(schedule, PrayerType.Isha,    2026, 3, 13,  3, 35);
    }

    /// <summary>Prayers must be in chronological order even when crossing midnight UTC.</summary>
    [Fact]
    public async Task MountainView_PrayerOrder_IsChronological()
    {
        var schedule = await ComputeSchedule(37.3861, -122.0839, 2026, 3, 12,
            CalculationMethod.MuslimWorldLeague);

        var ordered = schedule.Prayers.OrderBy(p => p.DateTime).ToList();
        for (int i = 1; i < ordered.Count; i++)
        {
            Assert.True(ordered[i].DateTime > ordered[i - 1].DateTime,
                $"{ordered[i].Type} ({ordered[i].DateTime:HH:mm}) must be after {ordered[i - 1].Type} ({ordered[i - 1].DateTime:HH:mm})");
        }
    }

    // ── Anchorage (extreme western longitude – all evening prayers cross midnight UTC) ──

    [Fact]
    public async Task Anchorage_MWL_EveningPrayersCrossMidnightUtc()
    {
        var schedule = await ComputeSchedule(61.2181, -149.9003, 2026, 3, 12,
            CalculationMethod.MuslimWorldLeague);

        AssertUtc(schedule, PrayerType.Fajr,    2026, 3, 12, 14, 38);
        AssertUtc(schedule, PrayerType.Dhuhr,   2026, 3, 12, 22,  9);
        AssertUtc(schedule, PrayerType.Asr,     2026, 3, 13,  0, 58);
        AssertUtc(schedule, PrayerType.Maghrib, 2026, 3, 13,  3, 56);
        AssertUtc(schedule, PrayerType.Isha,    2026, 3, 13,  5, 42);
    }

    // ── Makkah (eastern hemisphere, Umm al-Qura method) ─────────────────────

    [Fact]
    public async Task Makkah_UmmAlQura_AllTimesOnSameUtcDay()
    {
        var schedule = await ComputeSchedule(21.3891, 39.8579, 2026, 3, 12,
            CalculationMethod.UmmAlQura);

        AssertUtc(schedule, PrayerType.Fajr,    2026, 3, 12,  2, 16);
        AssertUtc(schedule, PrayerType.Dhuhr,   2026, 3, 12,  9, 30);
        AssertUtc(schedule, PrayerType.Asr,     2026, 3, 12, 12, 54);
        AssertUtc(schedule, PrayerType.Maghrib, 2026, 3, 12, 15, 30);
        AssertUtc(schedule, PrayerType.Isha,    2026, 3, 12, 17,  0);
    }

    // ── Sydney (southern hemisphere, eastern longitude) ──────────────────────

    [Fact]
    public async Task Sydney_MWL_EarlyPrayersFallOnPreviousUtcDay()
    {
        var schedule = await ComputeSchedule(-33.8688, 151.2093, 2026, 3, 12,
            CalculationMethod.MuslimWorldLeague);

        // For far-eastern longitudes (lon +151), early local prayers map to the
        // previous UTC day.  Fajr 4:27 AM AEDT (UTC+11) = 18:27 UTC March 11.
        // The algorithm starts from March 12 midnight UTC, so negative fractional
        // hours roll back to March 11.  This is correct — .ToLocalTime() will
        // convert them back to the right local date.
        AssertUtc(schedule, PrayerType.Fajr,    2026, 3, 11, 18, 27);
        AssertUtc(schedule, PrayerType.Dhuhr,   2026, 3, 12,  2,  5);
        AssertUtc(schedule, PrayerType.Asr,     2026, 3, 12,  5, 37);
        AssertUtc(schedule, PrayerType.Maghrib, 2026, 3, 12,  8, 19);
        AssertUtc(schedule, PrayerType.Isha,    2026, 3, 12,  9, 37);
    }

    // ── Schedule validity ────────────────────────────────────────────────────

    [Theory]
    [InlineData(37.3861, -122.0839, "Mountain View")]
    [InlineData(61.2181, -149.9003, "Anchorage")]
    [InlineData(21.3891, 39.8579,   "Makkah")]
    [InlineData(-33.8688, 151.2093, "Sydney")]
    [InlineData(51.5074, -0.1278,   "London")]
    public async Task Schedule_IsValid_ForVariousLocations(double lat, double lon, string label)
    {
        var schedule = await ComputeSchedule(lat, lon, 2026, 3, 12,
            CalculationMethod.MuslimWorldLeague);

        Assert.True(schedule.IsValid(), $"Schedule invalid for {label}");
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private async Task<DailyPrayerSchedule> ComputeSchedule(
        double lat, double lon, int year, int month, int day,
        CalculationMethod method, Madhab madhab = Madhab.Shafi)
    {
        var location = new LocationSnapshot(LocationMode.Manual, lat, lon);
        var date = new DateTimeOffset(year, month, day, 0, 0, 0, TimeSpan.Zero);
        var settings = new PrayerCalculationSettings
        {
            Method = method,
            Madhab = madhab,
            HighLatitudeRule = HighLatitudeRule.SeventhOfNight,
        };
        return await _calculator.CalculateDailyScheduleAsync(location, date, settings);
    }

    private static void AssertUtc(
        DailyPrayerSchedule schedule, PrayerType type,
        int year, int month, int day, int hour, int minute)
    {
        var prayer = schedule.Prayers.First(p => p.Type == type);
        var expected = new DateTimeOffset(year, month, day, hour, minute, 0, TimeSpan.Zero);
        var diff = Math.Abs((prayer.DateTime - expected).TotalMinutes);
        Assert.True(diff <= 1.0,
            $"{type}: expected {expected:yyyy-MM-dd HH:mm} UTC, got {prayer.DateTime:yyyy-MM-dd HH:mm} UTC " +
            $"(diff={diff:F1}min, raw={prayer.DateTime:O})");
    }
}
