using QiblaNow.Core.Models;

namespace QiblaNow.Core.Tests;

public class PrayerTimesCalculatorTests
{
    private readonly PrayerTimesCalculator _calculator = new();

    // ── Mountain View (western hemisphere – prayers cross midnight UTC) ──────

    /// <summary>
    /// Regression test for the primary bug: ToDate clamped hours > 23,
    /// corrupting Maghrib/Isha at western longitudes where UTC times exceed 24h.
    /// Reference values generated by PrayTimes JS v3.2 CLI.
    /// </summary>
    [Fact]
    public async Task MountainView_MWL_MaghribAndIsha_FallOnNextUtcDay()
    {
        var schedule = await ComputeSchedule(37.3861, -122.0839, 2026, 3, 12,
            CalculationMethod.MuslimWorldLeague);

        // Maghrib/Isha must be on March 13 UTC (next day) — not clamped to March 12
        AssertUtc(schedule, PrayerType.Fajr,    2026, 3, 12, 12, 57);
        AssertUtc(schedule, PrayerType.Sunrise,  2026, 3, 12, 14, 24);
        AssertUtc(schedule, PrayerType.Dhuhr,   2026, 3, 12, 20, 18);
        AssertUtc(schedule, PrayerType.Asr,     2026, 3, 12, 23, 39);
        AssertUtc(schedule, PrayerType.Maghrib, 2026, 3, 13,  2, 14);
        AssertUtc(schedule, PrayerType.Isha,    2026, 3, 13,  3, 35);
    }

    /// <summary>Prayers must be in chronological order even when crossing midnight UTC.</summary>
    [Fact]
    public async Task MountainView_PrayerOrder_IsChronological()
    {
        var schedule = await ComputeSchedule(37.3861, -122.0839, 2026, 3, 12,
            CalculationMethod.MuslimWorldLeague);

        var ordered = schedule.Prayers.OrderBy(p => p.DateTime).ToList();
        for (int i = 1; i < ordered.Count; i++)
        {
            Assert.True(ordered[i].DateTime > ordered[i - 1].DateTime,
                $"{ordered[i].Type} ({ordered[i].DateTime:HH:mm}) must be after {ordered[i - 1].Type} ({ordered[i - 1].DateTime:HH:mm})");
        }
    }

    // ── Anchorage (extreme western longitude – all evening prayers cross midnight UTC) ──

    [Fact]
    public async Task Anchorage_MWL_EveningPrayersCrossMidnightUtc()
    {
        var schedule = await ComputeSchedule(61.2181, -149.9003, 2026, 3, 12,
            CalculationMethod.MuslimWorldLeague);

        AssertUtc(schedule, PrayerType.Fajr,    2026, 3, 12, 14, 38);
        AssertUtc(schedule, PrayerType.Dhuhr,   2026, 3, 12, 22,  9);
        AssertUtc(schedule, PrayerType.Asr,     2026, 3, 13,  0, 58);
        AssertUtc(schedule, PrayerType.Maghrib, 2026, 3, 13,  3, 56);
        AssertUtc(schedule, PrayerType.Isha,    2026, 3, 13,  5, 42);
    }

    // ── Makkah (eastern hemisphere, Umm al-Qura method) ─────────────────────

    [Fact]
    public async Task Makkah_UmmAlQura_AllTimesOnSameUtcDay()
    {
        var schedule = await ComputeSchedule(21.3891, 39.8579, 2026, 3, 12,
            CalculationMethod.UmmAlQura);

        AssertUtc(schedule, PrayerType.Fajr,    2026, 3, 12,  2, 16);
        AssertUtc(schedule, PrayerType.Dhuhr,   2026, 3, 12,  9, 30);
        AssertUtc(schedule, PrayerType.Asr,     2026, 3, 12, 12, 54);
        AssertUtc(schedule, PrayerType.Maghrib, 2026, 3, 12, 15, 30);
        AssertUtc(schedule, PrayerType.Isha,    2026, 3, 12, 17,  0);
    }

    // ── Sydney (southern hemisphere, eastern longitude) ──────────────────────

    [Fact]
    public async Task Sydney_MWL_EarlyPrayersFallOnPreviousUtcDay()
    {
        var schedule = await ComputeSchedule(-33.8688, 151.2093, 2026, 3, 12,
            CalculationMethod.MuslimWorldLeague);

        // For far-eastern longitudes (lon +151), early local prayers map to the
        // previous UTC day.  Fajr 4:27 AM AEDT (UTC+11) = 18:27 UTC March 11.
        // The algorithm starts from March 12 midnight UTC, so negative fractional
        // hours roll back to March 11.  This is correct — .ToLocalTime() will
        // convert them back to the right local date.
        AssertUtc(schedule, PrayerType.Fajr,    2026, 3, 11, 18, 27);
        AssertUtc(schedule, PrayerType.Dhuhr,   2026, 3, 12,  2,  5);
        AssertUtc(schedule, PrayerType.Asr,     2026, 3, 12,  5, 37);
        AssertUtc(schedule, PrayerType.Maghrib, 2026, 3, 12,  8, 19);
        AssertUtc(schedule, PrayerType.Isha,    2026, 3, 12,  9, 37);
    }

    // ── Schedule validity ────────────────────────────────────────────────────

    [Theory]
    [InlineData(37.3861, -122.0839, "Mountain View")]
    [InlineData(61.2181, -149.9003, "Anchorage")]
    [InlineData(21.3891, 39.8579,   "Makkah")]
    [InlineData(-33.8688, 151.2093, "Sydney")]
    [InlineData(51.5074, -0.1278,   "London")]
    public async Task Schedule_IsValid_ForVariousLocations(double lat, double lon, string label)
    {
        var schedule = await ComputeSchedule(lat, lon, 2026, 3, 12,
            CalculationMethod.MuslimWorldLeague);

        Assert.True(schedule.IsValid(), $"Schedule invalid for {label}");
    }

    [Fact]
    public async Task NextPrayer_Rollover_IsAlwaysInTheFuture()
    {
        // Schedule for March 13 with prayers on March 13.
        var schedule = BuildScheduleForDay(new DateTimeOffset(2026, 3, 13, 0, 0, 0, TimeSpan.Zero));
        // 'now' is after all March 13 prayers.
        var now = new DateTimeOffset(2026, 3, 13, 21, 0, 0, TimeSpan.Zero);

        var result = await _calculator.CalculateNextPrayerAsync(schedule, new PrayerNotificationSettings(), now);

        Assert.NotNull(result);
        Assert.True(result!.Time > now);
        // The +24h rollover picks Fajr — acceptable for the approximate contract.
        Assert.Equal(PrayerType.Fajr, result.Type);
        Assert.False(result.IsToday);
    }

    [Fact]
    public async Task Countdown_MatchesNextPrayer_TargetAndRemainingSeconds()
    {
        var schedule = BuildScheduleForDay(new DateTimeOffset(2026, 3, 13, 0, 0, 0, TimeSpan.Zero));
        // 'now' is before Dhuhr, so Dhuhr is the next prayer within the schedule.
        var now = new DateTimeOffset(2026, 3, 13, 9, 34, 0, TimeSpan.Zero);

        var next = await _calculator.CalculateNextPrayerAsync(schedule, new PrayerNotificationSettings(), now);
        var countdown = await _calculator.CalculateCountdownAsync(schedule, new PrayerNotificationSettings(), now);

        Assert.NotNull(next);
        Assert.NotNull(countdown);
        Assert.Equal(next!.Type, countdown!.Type);
        Assert.Equal(next.Time, countdown.TargetTime);
        Assert.Equal((int)Math.Round((next.Time - now).TotalSeconds), countdown.RemainingSeconds);
    }

    // ── Single-schedule helpers (no rollover) ────────────────────────────────

    [Fact]
    public void FindNextPrayer_ReturnsFirstFuturePrayer()
    {
        var schedule = BuildScheduleForDay(new DateTimeOffset(2026, 3, 13, 0, 0, 0, TimeSpan.Zero));
        var now = new DateTimeOffset(2026, 3, 13, 9, 0, 0, TimeSpan.Zero);
        var enabled = AllPrayerTypes();

        var result = _calculator.FindNextPrayerInSchedule(schedule, enabled, now);

        Assert.NotNull(result);
        Assert.Equal(PrayerType.Dhuhr, result!.Value.Type);
    }

    [Fact]
    public void FindNextPrayer_ReturnsNull_WhenScheduleExhausted()
    {
        var schedule = BuildScheduleForDay(new DateTimeOffset(2026, 3, 13, 0, 0, 0, TimeSpan.Zero));
        var now = new DateTimeOffset(2026, 3, 13, 21, 0, 0, TimeSpan.Zero);
        var enabled = AllPrayerTypes();

        var result = _calculator.FindNextPrayerInSchedule(schedule, enabled, now);

        Assert.Null(result);
    }

    [Fact]
    public void FindFirstEnabled_ReturnsFirstChronologicalPrayer()
    {
        var schedule = BuildScheduleForDay(new DateTimeOffset(2026, 3, 13, 0, 0, 0, TimeSpan.Zero));
        var enabled = AllPrayerTypes();

        var result = _calculator.FindFirstEnabledPrayer(schedule, enabled);

        Assert.NotNull(result);
        Assert.Equal(PrayerType.Fajr, result!.Value.Type);
    }

    // ── Two-schedule orchestration (the real Home flow) ──────────────────────

    [Fact]
    public async Task Orchestration_AfterIsha_TargetIsTomorrowFajr_FromRealSchedule()
    {
        // This models the exact Home flow: today is exhausted, so compute
        // tomorrow's schedule explicitly and pick its first enabled prayer.
        var todayDate    = new DateTimeOffset(2026, 3, 13, 0, 0, 0, TimeSpan.Zero);
        var tomorrowDate = new DateTimeOffset(2026, 3, 14, 0, 0, 0, TimeSpan.Zero);

        // Makkah, Umm al-Qura — easy location, all prayers on same UTC day.
        var location = new LocationSnapshot(LocationMode.Manual, 21.3891, 39.8579);
        var settings = new PrayerCalculationSettings
        {
            Method = CalculationMethod.UmmAlQura,
            Madhab = Madhab.Shafi,
            HighLatitudeRule = HighLatitudeRule.SeventhOfNight,
        };
        var enabled = AllPrayerTypes();

        var todaySchedule    = await _calculator.CalculateDailyScheduleAsync(location, todayDate, settings);
        var tomorrowSchedule = await _calculator.CalculateDailyScheduleAsync(location, tomorrowDate, settings);

        // 'now' is after Isha on March 13.
        var now = new DateTimeOffset(2026, 3, 13, 18, 0, 0, TimeSpan.Zero);

        // Step 1: search today → null.
        var todayNext = _calculator.FindNextPrayerInSchedule(todaySchedule, enabled, now);
        Assert.Null(todayNext);

        // Step 2: fallback to tomorrow's first enabled prayer.
        var tomorrowFirst = _calculator.FindFirstEnabledPrayer(tomorrowSchedule, enabled);
        Assert.NotNull(tomorrowFirst);
        Assert.Equal(PrayerType.Fajr, tomorrowFirst!.Value.Type);

        // The target must actually be in the future relative to 'now'.
        Assert.True(tomorrowFirst.Value.DateTime > now,
            $"Tomorrow Fajr {tomorrowFirst.Value.DateTime:u} should be after now {now:u}");

        // Target date should be March 14, not March 13 + 24h approximation.
        Assert.Equal(14, tomorrowFirst.Value.DateTime.Day);
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private async Task<DailyPrayerSchedule> ComputeSchedule(
        double lat, double lon, int year, int month, int day,
        CalculationMethod method, Madhab madhab = Madhab.Shafi)
    {
        var location = new LocationSnapshot(LocationMode.Manual, lat, lon);
        var date = new DateTimeOffset(year, month, day, 0, 0, 0, TimeSpan.Zero);
        var settings = new PrayerCalculationSettings
        {
            Method = method,
            Madhab = madhab,
            HighLatitudeRule = HighLatitudeRule.SeventhOfNight,
        };
        return await _calculator.CalculateDailyScheduleAsync(location, date, settings);
    }

    private static void AssertUtc(
        DailyPrayerSchedule schedule, PrayerType type,
        int year, int month, int day, int hour, int minute)
    {
        var prayer = schedule.Prayers.First(p => p.Type == type);
        var expected = new DateTimeOffset(year, month, day, hour, minute, 0, TimeSpan.Zero);
        var diff = Math.Abs((prayer.DateTime - expected).TotalMinutes);
        Assert.True(diff <= 1.0,
            $"{type}: expected {expected:yyyy-MM-dd HH:mm} UTC, got {prayer.DateTime:yyyy-MM-dd HH:mm} UTC " +
            $"(diff={diff:F1}min, raw={prayer.DateTime:O})");
    }

    /// <summary>
    /// Builds a synthetic schedule whose <see cref="DailyPrayerSchedule.Date"/>
    /// and prayer instants all belong to the same civil UTC day.
    /// </summary>
    private static DailyPrayerSchedule BuildScheduleForDay(DateTimeOffset date)
    {
        var schedule = new DailyPrayerSchedule(date, TimeZoneInfo.Utc);
        schedule.Prayers.Add(new PrayerTime(PrayerType.Fajr,    date.AddHours(6).AddMinutes(1)));
        schedule.Prayers.Add(new PrayerTime(PrayerType.Sunrise, date.AddHours(7).AddMinutes(30)));
        schedule.Prayers.Add(new PrayerTime(PrayerType.Dhuhr,   date.AddHours(13).AddMinutes(25)));
        schedule.Prayers.Add(new PrayerTime(PrayerType.Asr,     date.AddHours(16).AddMinutes(43)));
        schedule.Prayers.Add(new PrayerTime(PrayerType.Maghrib, date.AddHours(19).AddMinutes(19)));
        schedule.Prayers.Add(new PrayerTime(PrayerType.Isha,    date.AddHours(20).AddMinutes(44)));
        return schedule;
    }

    private static HashSet<PrayerType> AllPrayerTypes() => new()
    {
        PrayerType.Fajr,
        PrayerType.Dhuhr,
        PrayerType.Asr,
        PrayerType.Maghrib,
        PrayerType.Isha,
    };
}
